# Configuración de Netlify para Colegio Liahona

[build]
  # Directorio donde están los archivos del sitio
  publish = "."
  
  # No hay proceso de build ya que es un sitio estático
  command = ""

# Configuración para URLs limpias
[[redirects]]
  from = "/*"
  to = "/:splat.html"
  status = 200
  conditions = {Language = ["es"]}

# Redirecciones específicas para páginas sin extensión
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Redirección para el panel de administración
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self' https:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://identity.netlify.com https://cdn.jsdelivr.net;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https: blob:;
      connect-src 'self' https://api.github.com;
      frame-src 'self' https://www.youtube.com https://player.vimeo.com;
    """

# Cache control para assets estáticos
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/upload/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configuración específica para el CMS
[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Funciones serverless (para futuras expansiones)
[functions]
  directory = "functions"

# Variables de entorno (se configuran en el panel de Netlify)
[context.production.environment]
  NODE_ENV = "production"

# Branch deploy settings
[context.branch-deploy]
  command = ""

# Deploy Preview settings
[context.deploy-preview]
  command = ""